# Generated by Django 3.1.1 on 2020-12-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201201_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_phone', models.CharField(max_length=11)),
                ('collection_module_type', models.CharField(max_length=5)),
                ('collection_module_id', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_phone', models.CharField(max_length=11)),
                ('history_module_type', models.CharField(max_length=5)),
                ('history_module_id', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
    ]
