# Generated by Django 3.1.1 on 2020-12-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usercollection_userhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercollection',
            options={'ordering': ('id', 'create_time')},
        ),
        migrations.AlterModelOptions(
            name='userhistory',
            options={'ordering': ('id', 'create_time')},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
