# Generated by Django 3.1.1 on 2020-12-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybasicinformation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
