# Generated by Django 3.1.1 on 2020-12-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_database', '0002_auto_20201201_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybasicinformation',
            old_name='deteled',
            new_name='deleted',
        ),
        migrations.AddField(
            model_name='companyfinancedata',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
